# Generated by Django 5.0.4 on 2024-12-14 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis',
            name='bekleme_baslangic',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='siparis',
            name='oncelik_skoru',
            field=models.FloatField(default=0),
        ),
    ]
