# Generated by Django 5.0.4 on 2024-12-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilk', '0003_sistemdurumu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musteri',
            name='toplam_harcama',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
